name: Run Ansible playbook on VM

on:
  workflow_dispatch:   # запуск руками из GitHub

jobs:
  deploy:
    runs-on: self-hosted   # наш self-hosted runner на ВМ

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show files (debug)
        run: |
          pwd
          ls -l

      - name: Run Ansible playbook
        run: |
          cd $GITHUB_WORKSPACE
          ansible-playbook -i inventory.ini site.yml
